[general]
import = ["~/.config/alacritty/cyberpunk-umbra-alacritty.toml"]

[window]
option_as_alt = "Both"
opacity=0.95

[font]
size = 11.0

[font.normal]
family = "IBM Plex Mono"
style = "Regular"

[font.bold]
family = "IBM Plex Mono"
style = "Bold"

[font.italic]
family = "IBM Plex Mono"
style = "Italic"

[font.bold_italic]
family = "IBM Plex Mono"
style = "Bold Italic"

[[keyboard.bindings]]
key = "T"
mods = "Command"
action = "CreateNewWindow" # Changes Cmd+T from opening a tab to a new window
