# Cyberpunk theme, based on the VS Code theme
#
# Main Colors
foreground           #EEFFFF
background           #261D45
selection_background #311b92
selection_foreground #ffffff

# Cursor
cursor               #9dff00
cursor_text_color    #261D45

# ANSI Colors (16-color palette)
# Black
color0               #1E1D45
color8               #6766b3

# Red
color1               #FF5370
color9               #ff3270

# Green
color2               #00ff6a
color10              #9dff00

# Yellow
color3               #fffc58
color11              #ffff00

# Blue
color4               #00b0ff
color12              #76c1ff

# Magenta
color5               #d57bff
color13              #ee6dff

# Cyan
color6               #00ffc8
color14              #98e3ff

# White
color7               #EEFFFF
color15              #ffffff

